// app/i18n/translations.js
// Traducciones completas Español / Inglés

export const translations = {
  es: {
    // === AUTH ===
    auth: {
      login: 'Iniciar Sesión',
      register: 'Crear Cuenta',
      email: 'Correo Electrónico',
      password: 'Contraseña',
      fullName: 'Nombre Completo',
      phone: 'Número de Teléfono',
      birthDate: 'Fecha de Nacimiento',
      gender: 'Sexo',
      male: 'Hombre',
      female: 'Mujer',
      verifyEmail: 'Verificar Correo',
      verifyPhone: 'Verificar Teléfono',
      enterCode: 'Ingresa el código de verificación',
      codeSentEmail: 'Te enviamos un código a tu correo',
      codeSentPhone: 'Te enviamos un SMS con el código',
      forgotPassword: '¿Olvidaste tu contraseña?',
      alreadyHaveAccount: '¿Ya tienes cuenta? Inicia sesión',
      noAccount: '¿No tienes cuenta? Regístrate',
      verify: 'Verificar',
      resendCode: 'Reenviar código',
      passwordMinLength: 'La contraseña debe tener al menos 8 caracteres',
      passwordUppercase: 'Debe incluir al menos una mayúscula',
      passwordNumber: 'Debe incluir al menos un número',
    },

    // === HOME ===
    home: {
      greeting: 'Buenos días',
      greetingAfternoon: 'Buenas tardes',
      greetingEvening: 'Buenas noches',
      todayHabits: 'Mis hábitos de hoy',
      weeklyProgress: 'Progreso semanal',
      noHabitsYet: 'Aún no tienes hábitos. ¡Crea uno!',
      createNewHabit: 'Crear nuevo hábito',
      completed: 'Completado',
      pending: 'Pendiente',
      streak: 'días seguidos',
    },

    // === ASSISTANT ===
    assistant: {
      title: 'Mi Asistente',
      subtitle: 'Tu guía personal de hábitos',
      greeting: '¡Hola! Soy tu asistente personal. ¿En qué meta quieres trabajar hoy?',
      newMind: 'Nueva Meta',
      myGoals: 'Mis Metas',
      freeLimit: 'Has alcanzado el límite de 3 metas gratuitas.',
      upgradePrompt: '¡Actualiza a Premium para metas ilimitadas!',
      upgradePremium: 'Actualizar a Premium',
      askGoal: '¿Cuál es tu meta?',
      askFrequency: '¿Con qué frecuencia quieres hacerlo?',
      askTime: '¿A qué hora del día?',
      askDays: '¿Qué días de la semana?',
      planCreated: '¡Perfecto! Tu plan ha sido creado.',
      daily: 'Todos los días',
      weekdays: 'Lunes a Viernes',
      custom: 'Días específicos',
    },

    // === CHAT ===
    chat: {
      title: 'Chat',
      searchContacts: 'Buscar contactos',
      typeMessage: 'Escribe un mensaje...',
      sendAudio: 'Mensaje de voz',
      sendImage: 'Enviar foto',
      noMessages: 'Aún no hay mensajes. ¡Di hola!',
      friendsUsing: 'Amigos usando la app',
      addFriend: 'Agregar amigo',
      blockUser: 'Bloquear usuario',
      reportUser: 'Reportar usuario',
    },

    // === DEVOTIONAL ===
    devotional: {
      title: 'Devocional',
      todayVerse: 'Versículo del día',
      reflection: 'Reflexión',
      myNotes: 'Mis notas',
      saveNote: 'Guardar nota',
      share: 'Compartir',
    },

    // === STORIES ===
    stories: {
      title: 'Historias',
      myStory: 'Mi historia',
      share: 'Compartir logro',
      friendsStories: 'Historias de amigos',
      noStories: 'Aún no hay historias. ¡Comparte tu primer logro!',
      like: 'Me inspira',
      comment: 'Comentar',
    },

    // === WEEKLY RECORD ===
    weekly: {
      title: 'Registro Semanal',
      thisWeek: 'Esta semana',
      thisMonth: 'Este mes',
      achieved: 'Logros alcanzados',
      percentage: 'Porcentaje completado',
      certificate: '¡Felicidades!',
      certificateMsg: 'Completaste el {percent}% de tu meta semanal',
      certificateMonthMsg: 'Completaste el {percent}% de tu meta mensual',
      keepGoing: '¡Sigue así!',
      shareAchievement: 'Compartir logro',
    },

    // === NAVIGATION ===
    nav: {
      home: 'Inicio',
      assistant: 'Asistente',
      chat: 'Chat',
      stories: 'Historias',
      profile: 'Perfil',
      devotional: 'Devocional',
      weekly: 'Registro',
    },

    // === COMMON ===
    common: {
      save: 'Guardar',
      cancel: 'Cancelar',
      delete: 'Eliminar',
      edit: 'Editar',
      confirm: 'Confirmar',
      loading: 'Cargando...',
      error: 'Error',
      success: 'Éxito',
      yes: 'Sí',
      no: 'No',
      ok: 'Aceptar',
      back: 'Regresar',
      next: 'Siguiente',
      skip: 'Omitir',
      done: 'Listo',
    },
  },

  en: {
    auth: {
      login: 'Sign In',
      register: 'Create Account',
      email: 'Email Address',
      password: 'Password',
      fullName: 'Full Name',
      phone: 'Phone Number',
      birthDate: 'Date of Birth',
      gender: 'Gender',
      male: 'Male',
      female: 'Female',
      verifyEmail: 'Verify Email',
      verifyPhone: 'Verify Phone',
      enterCode: 'Enter verification code',
      codeSentEmail: 'We sent a code to your email',
      codeSentPhone: 'We sent you an SMS with the code',
      forgotPassword: 'Forgot your password?',
      alreadyHaveAccount: 'Already have an account? Sign in',
      noAccount: "Don't have an account? Sign up",
      verify: 'Verify',
      resendCode: 'Resend code',
      passwordMinLength: 'Password must be at least 8 characters',
      passwordUppercase: 'Must include at least one uppercase letter',
      passwordNumber: 'Must include at least one number',
    },
    home: {
      greeting: 'Good morning',
      greetingAfternoon: 'Good afternoon',
      greetingEvening: 'Good evening',
      todayHabits: "Today's habits",
      weeklyProgress: 'Weekly progress',
      noHabitsYet: 'No habits yet. Create one!',
      createNewHabit: 'Create new habit',
      completed: 'Completed',
      pending: 'Pending',
      streak: 'day streak',
    },
    assistant: {
      title: 'My Assistant',
      subtitle: 'Your personal habit guide',
      greeting: 'Hi! I am your personal assistant. What goal do you want to work on today?',
      newMind: 'New Goal',
      myGoals: 'My Goals',
      freeLimit: "You've reached the 3 free goals limit.",
      upgradePrompt: 'Upgrade to Premium for unlimited goals!',
      upgradePremium: 'Upgrade to Premium',
      askGoal: 'What is your goal?',
      askFrequency: 'How often do you want to do it?',
      askTime: 'What time of day?',
      askDays: 'Which days of the week?',
      planCreated: 'Perfect! Your plan has been created.',
      daily: 'Every day',
      weekdays: 'Monday to Friday',
      custom: 'Specific days',
    },
    chat: {
      title: 'Chat',
      searchContacts: 'Search contacts',
      typeMessage: 'Type a message...',
      sendAudio: 'Voice message',
      sendImage: 'Send photo',
      noMessages: 'No messages yet. Say hello!',
      friendsUsing: 'Friends using the app',
      addFriend: 'Add friend',
      blockUser: 'Block user',
      reportUser: 'Report user',
    },
    devotional: {
      title: 'Devotional',
      todayVerse: "Today's verse",
      reflection: 'Reflection',
      myNotes: 'My notes',
      saveNote: 'Save note',
      share: 'Share',
    },
    stories: {
      title: 'Stories',
      myStory: 'My story',
      share: 'Share achievement',
      friendsStories: "Friends' stories",
      noStories: 'No stories yet. Share your first achievement!',
      like: 'Inspiring',
      comment: 'Comment',
    },
    weekly: {
      title: 'Weekly Record',
      thisWeek: 'This week',
      thisMonth: 'This month',
      achieved: 'Achievements',
      percentage: 'Completion percentage',
      certificate: 'Congratulations!',
      certificateMsg: 'You completed {percent}% of your weekly goal',
      certificateMonthMsg: 'You completed {percent}% of your monthly goal',
      keepGoing: 'Keep it up!',
      shareAchievement: 'Share achievement',
    },
    nav: {
      home: 'Home',
      assistant: 'Assistant',
      chat: 'Chat',
      stories: 'Stories',
      profile: 'Profile',
      devotional: 'Devotional',
      weekly: 'Record',
    },
    common: {
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      confirm: 'Confirm',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      yes: 'Yes',
      no: 'No',
      ok: 'OK',
      back: 'Back',
      next: 'Next',
      skip: 'Skip',
      done: 'Done',
    },
  },
};
